[package]
authors = ["Scott Chamberlain"]
name = "rt-cli"
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.87"
argh = "0.1.12"
glob = "0.3.1"
regex = "1.10.6"
semver = "1.0.23"

[[bin]]
name = "rt"
path = "src/main.rs"
